### ISSUE TITLE
Issue with the branch the script checks out

### ISSUE THREAD

**Issue by traceyr** [giodamelio/download_pr_userscript#2]
When I run your script and copy it to the clipboard, the branch that it checks out is not the branch in the pull request, but instead it checks out a branch that is the name of the github account. Example code: 
git clone https://github.com/smitzter/salmon-cookie; cd salmon-cookie; git fetch origin pull/1/head:smitzter; git checkout smitzter;

**Comment by giodamelio** [comment]
Fixed
